### PR TITLE
Fixed old import from class-transformer

### PR DESCRIPTION
**Pull request by Niggl1999**
Since class-transformer@0.3.2 the `class-transformer/metadata/MetadataStorage` got moved to `class-transformer/types/MetadataStorage`.
https://uiwjs.github.io/npm-unpkg/#/pkg/class-transformer@0.3.1
https://uiwjs.github.io/npm-unpkg/#/pkg/class-transformer@0.3.2

This import change should fix it.

We discovered this b/c our builds failed with this error:
```
node_modules/.pnpm/class-validator-jsonschema@2.1.0_3355ee6f645742ea3fc0591706016b64/node_modules/class-validator-jsonschema/build/options.d.ts(1,68): error TS2307: Cannot find module 'class-transformer/metadata/MetadataStorage' or its corresponding type declarations.
 ERROR  Command failed with exit code 2.
ERROR: Service '<<SERVICE>>' failed to build : The command '/bin/sh -c pnpm run build' returned a non-zero code: 1
```

### CODE REVIEW

File: package.json [hunk 1]
```diff
@@ -53,7 +53,7 @@
     "typescript": "^4.1.3"
   },
   "peerDependencies": {
-    "class-transformer": "^0.2.3",
+    "class-transformer": "0.3.1",
```
Comment (epiphone) [inline package.json:56]:
```suggestion
    "class-transformer": "0.2.3 - 0.3.1",
```

How about this to still allow the previously allowed versions?

**Review by epiphone — CHANGES_REQUESTED** [review]
Ah that sucks... thanks for the fix though!

File: package.json (hunk 1 above)
Comment (Niggl1999) [reply package.json:56]: Just imo: I prefer not leaving people with old versions of dependencies, if I don't have to.

After looking at the class-transformer changelog and version history: There is no version between 0.2.3 and 0.3.1.
Therefore locking it to 0.3.1 would just be a dependency bump to the "next" version.

If you insist on allowing the previous version, I'll comply - it's just not my style :)

Just for reference:
* Class Transformer Tags: https://github.com/typestack/class-transformer/tags
* Class Transformer Changelog: https://github.com/typestack/class-transformer/blob/develop/CHANGELOG.md

Comment (epiphone) [reply package.json:56]: My thinking is that since this library works fine with `class-transformer@0.2.3` there's no reason to throw `incompatible peer dependency` errors to folks using that version: it's up to them to upgrade or not.

If `class-transformer` was a direct (non-peer) dependency here then we'd bump the version for sure.

**Comment by epiphone** [comment]
Released in https://github.com/epiphone/class-validator-jsonschema/releases/tag/v2.1.1
