### ISSUE TITLE
Not compatible with class-validator v0.12.0

### ISSUE THREAD

**Issue by leeuwd** [epiphone/class-validator-jsonschema#31]
`class-validator v0.12.0` has been releases as of 18-04-2020. `class-validator-jsonschema` is not compatible because of breaking changes, see [changelog](https://github.com/typestack/class-validator/blob/master/CHANGELOG.md).

To be specific:

```typescript
import { ValidationMetadata } from 'class-validator/metadata/ValidationMetadata';
```

needs to be replaced by

```typescript
import { ValidationMetadata } from 'class-validator/types/metadata/ValidationMetadata'
```

**Comment by epiphone** [comment]
Welp, looks like there's been a bunch of changes in `class-validator` besides that import path.

I'm working on v0.12 support in https://github.com/epiphone/class-validator-jsonschema/pull/32, mind giving it a shot in your project and telling me whether anything breaks? `yarn add epiphone/class-validator-jsonschema#class-validator-0.12` should get it installed.

**Comment by objmj-itminds** [comment]
I am just here to test this out as I too have just upgraded to class validator 0.12.0
Without doing anything but installing from the different branch there is a little path issue

```bash
λ yarn start
yarn run v1.19.2
$ ts-node index.ts
Error: Cannot find module 'C:\Users\mjh\dev\infoscreen\infoscreen-dashboard-widgets\src\node_modules\class-validator-jsonschema\build\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:323:19)
``` 

I had to cd into the node_modules dir and simple run `yarn && yarn build`

Now it works.!!!
My schema is being outputted as before.

**Comment by leeuwd** [comment]
Same here, after installing `epiphone/class-validator-jsonschema#class-validator-0.12`:

```
TS2307: Cannot find module 'class-validator-jsonschema'.
```

**Comment by epiphone** [comment]
Alright, I baked together a pre-release. Can you try `yarn add class-validator-jsonschema@next` and let me know how it works?

I also released `routing-controllers-openapi@next` if you're using that.

**Comment by leeuwd** [comment]
> Alright, I baked together a pre-release. Can you try `yarn add class-validator-jsonschema@next` and let me know how it works?
> 
> I also released `routing-controllers-openapi@next` if you're using that.
> 
> Note the API changes: https://github.com/epiphone/class-validator-jsonschema/blob/class-validator-0.12/CHANGELOG.md#200-rc1---2020-05-01

Working flawless!

**Comment by epiphone** [comment]
Cool cool, released in v2.0.0
